### ISSUE TITLE
Choosing skin gives errors

### ISSUE THREAD

**Issue by panther2** [triplea-maps/middle_earth-map_skin2#2]
triplea.engine.version.bin:1.9
Loading map: middle_earth, from: C:\Users\User\triplea\downloadedMaps\middle_earth-master.zip
Loading map: middle_earth, from: C:\Users\User\triplea\downloadedMaps\middle_earth-master.zip
Loading map: middle_earth-master, from: C:\Users\User\triplea\downloadedMaps\middle_earth-master.zip
Error Changing Map Skin2
java.lang.NullPointerException
    at games.strategy.util.PointFileReaderWriter.readOneToManyPolygons(PointFileReaderWriter.java:207)
    at games.strategy.triplea.ui.mapdata.MapData.<init>(MapData.java:153)
    at games.strategy.triplea.ui.UIContext.internalSetMapDir(UIContext.java:77)
    at games.strategy.triplea.ui.AbstractUIContext.setMapDir(AbstractUIContext.java:122)
    at games.strategy.triplea.ui.TripleAFrame.updateMap(TripleAFrame.java:2082)
    at games.strategy.triplea.ui.menubar.ViewMenu.lambda$addMapSkinsMenu$667(ViewMenu.java:295)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:353)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DanVanAtta** [comment]
This is a game engine problem, should be fixed after: https://github.com/triplea-game/triplea/pull/1204

**Comment by panther2** [comment]
Fixed and closed, thanks.
